# Generated by Django 5.1.3 on 2025-01-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bestsellingphone',
            new_name='bestselling',
        ),
    ]
