# Generated by Django 5.1.3 on 2025-01-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_bestsellingphone_bestselling'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestselling',
            name='battery',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bestselling',
            name='camera',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bestselling',
            name='overview',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='bestselling',
            name='ram',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bestselling',
            name='rom',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
