# Generated by Django 5.1.3 on 2025-01-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_brand_mobiles_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobiles",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobiles",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="mobiles",
            name="emi_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mobiles",
            name="image",
            field=models.ImageField(upload_to="mobiles/"),
        ),
        migrations.AlterField(
            model_name="mobiles",
            name="origprice",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="slides",
            name="img",
            field=models.ImageField(upload_to="slides/"),
        ),
    ]
