# Generated by Django 5.1.3 on 2025-02-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_mobiles_delivery_date_mobiles_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off', models.IntegerField()),
                ('img', models.ImageField(upload_to='media/')),
                ('name', models.CharField(max_length=50)),
                ('off_price', models.IntegerField()),
                ('old_price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='slides',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
