# Generated by Django 5.1.3 on 2025-02-04 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_offer_alter_slides_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='laptops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mobiles/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('origprice', models.IntegerField(null=True)),
                ('dispaly', models.CharField(max_length=100, null=True)),
                ('memory', models.CharField(max_length=100, null=True)),
                ('processor', models.CharField(max_length=100, null=True)),
                ('os', models.CharField(max_length=100, null=True)),
                ('overview', models.TextField(max_length=3000, null=True)),
                ('is_bestselling', models.BooleanField(default=False, null=True)),
                ('is_deals', models.BooleanField(default=False, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('emi_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.brand')),
            ],
        ),
    ]
