# Generated by Django 5.1.3 on 2025-02-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_lapbrand_alter_laptops_image_alter_laptops_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptops',
            old_name='dispaly',
            new_name='display',
        ),
    ]
