# Generated by Django 5.1.3 on 2025-02-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_rename_dispaly_laptops_display"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accessories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="accessories/")),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Newly_lanched", models.BooleanField(default=False, null=True)),
                ("orginalprice", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
