# Generated by Django 5.1.3 on 2025-02-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_accessories"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessories",
            name="Brand",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="accessories",
            name="lanch_year",
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="accessories",
            name="warrenty",
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
