# Generated by Django 5.1.3 on 2025-02-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_accessories_brand_accessories_lanch_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='lanch_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='warrenty',
            field=models.IntegerField(null=True),
        ),
    ]
